# Form implementation generated from reading ui file '.\resources\static\loading_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 480, 221))
        self.main_frame.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0.364964 rgba(255, 198, 0, 189), stop:0.378102 rgba(194, 255, 0, 183), stop:0.392701 rgba(130, 255, 0, 183), stop:0.405839 rgba(23, 255, 31, 203), stop:0.421898 rgba(23, 255, 97, 203), stop:0.445255 rgba(54, 255, 209, 227), stop:0.459854 rgba(54, 202, 255, 227), stop:0.471533 rgba(54, 137, 255, 227), stop:0.484672 rgba(168, 54, 255, 227), stop:0.50073 rgba(254, 92, 255, 255), stop:0.556204 rgba(255, 0, 31, 130), stop:0.610219 rgba(255, 0, 0, 255));\n"
"border-radius: 40%;\n"
"border: 10px solid;\n"
"border-color: rgb(192, 0, 192);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.progressBar = QtWidgets.QProgressBar(self.main_frame)
        self.progressBar.setGeometry(QtCore.QRect(50, 150, 341, 41))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: none;\n"
"    border-radius: 20%;\n"
"    background-color: #ffe7ef;\n"
"    color: white;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 20%;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.347, x2:1, y2:0.432, stop:0 rgba(255, 0, 0, 255), stop:0.164773 rgba(255, 255, 0, 255), stop:0.329545 rgba(0, 255, 0, 255), stop:0.471591 rgba(0, 255, 255, 255), stop:0.647727 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.icon_frame = QtWidgets.QFrame(self.centralwidget)
        self.icon_frame.setGeometry(QtCore.QRect(360, 60, 231, 231))
        self.icon_frame.setStyleSheet("image: url(:/img/brush.png);")
        self.icon_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.icon_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.icon_frame.setObjectName("icon_frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Canvas..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
