# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\project\test\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


    # ProjectCanvas = QtWidgets.QMainWindow()
    #     ProjectCanvas = self.ProjectCanvas


class Ui_ProjectCanvas(object):

    def setupUi(self, ProjectCanvas):
        ProjectCanvas.setObjectName("ProjectCanvas")
        ProjectCanvas.resize(1074, 717)
        # ProjectCanvas.setWindoñwTitle("ProjectCanvas")
        self.centralwidget = QtWidgets.QWidget(ProjectCanvas)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        ProjectCanvas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectCanvas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEditor = QtWidgets.QMenu(self.menubar)
        self.menuEditor.setObjectName("menuEditor")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        ProjectCanvas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectCanvas)
        self.statusbar.setObjectName("statusbar")
        ProjectCanvas.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(ProjectCanvas)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(ProjectCanvas)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEditor.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(ProjectCanvas)
        QtCore.QMetaObject.connectSlotsByName(ProjectCanvas)

    def retranslateUi(self, ProjectCanvas):
        _translate = QtCore.QCoreApplication.translate
        ProjectCanvas.setWindowTitle(_translate("ProjectCanvas", "ProjectCanvas"))
        self.menuFile.setTitle(_translate("ProjectCanvas", "File"))
        self.menuEditor.setTitle(_translate("ProjectCanvas", "Editor"))
        self.menuView.setTitle(_translate("ProjectCanvas", "View"))
        self.actionOpen.setText(_translate("ProjectCanvas", "Open"))
        self.actionSave.setText(_translate("ProjectCanvas", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectCanvas = QtWidgets.QMainWindow()
    ui = Ui_ProjectCanvas()
    ui.setupUi(ProjectCanvas)
    ProjectCanvas.show()
    sys.exit(app.exec_())
