# Form implementation generated from reading ui file '.\pyQt6\event_handling_example.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadTest(object):
    def setupUi(self, LoadTest):
        LoadTest.setObjectName("LoadTest")
        LoadTest.resize(844, 585)
        self.pushButton = QtWidgets.QPushButton(LoadTest)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.pushButton.setStyleSheet("background-color: rgb(160, 160, 220);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 32%;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.set_text)
        self.lineEdit = QtWidgets.QLineEdit(LoadTest)
        self.lineEdit.setGeometry(QtCore.QRect(240, 40, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(153, 161, 148);")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(LoadTest)
        QtCore.QMetaObject.connectSlotsByName(LoadTest)

        self.text_browser = QtWidgets.QTextBrowser(LoadTest)
        self.text_browser.setGeometry(QtCore.QRect(20, 110, 731, 441))

    def retranslateUi(self, LoadTest):
        _translate = QtCore.QCoreApplication.translate
        LoadTest.setWindowTitle(_translate("LoadTest", "LoadTest"))
        self.pushButton.setText(_translate("LoadTest", "PushButton"))
        self.lineEdit.setText(_translate("LoadTest", "ndsmdmnasn"))


    def set_text(self):
        self.text_browser.setText(self.lineEdit.displayText())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadTest = QtWidgets.QWidget()
    ui = Ui_LoadTest()
    ui.setupUi(LoadTest)
    LoadTest.show()
    sys.exit(app.exec())
